name: SSH Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VULTR_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VULTR_PORT }} -H ${{ secrets.VULTR_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -p ${{ secrets.VULTR_PORT }} \
          ${{ secrets.VULTR_USER }}@${{ secrets.VULTR_HOST }} \
          "whoami && hostname && pwd"